# Generated by Django 4.0.5 on 2023-07-01 07:40

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fav_service',
            field=models.ManyToManyField(blank=True, related_name='fav_sp', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(max_length=100)),
                ('service_overview', models.CharField(max_length=1000, null=True)),
                ('service_image', models.ImageField(default='default.png', upload_to=account.models.get_image_filename)),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gigs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gig_name', models.CharField(max_length=100)),
                ('gig_description', models.CharField(max_length=1000, null=True)),
                ('gig_price', models.CharField(max_length=20, null=True)),
                ('gig_negotiable', models.BooleanField(default=False, verbose_name='Negotiable')),
                ('gig_location', models.CharField(max_length=20, null=True)),
                ('gig_service_type', models.CharField(max_length=20, null=True)),
                ('gig_image', models.ImageField(default='default.png', upload_to=account.models.get_image_filename)),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='fav_gigs',
            field=models.ManyToManyField(blank=True, related_name='fav_gig', to='account.gigs'),
        ),
    ]
