# Generated by Django 4.0.5 on 2023-07-06 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_tokens_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gigs',
            name='service_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gigs', to=settings.AUTH_USER_MODEL),
        ),
    ]
