# Generated by Django 4.0.5 on 2023-07-31 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0001_initial'),
        ('account', '0007_alter_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gigs',
            name='service_provider',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='service_provider',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='fav_gigs',
            field=models.ManyToManyField(blank=True, related_name='fav_gig', to='gigs.gigs'),
        ),
        migrations.DeleteModel(
            name='Business',
        ),
        migrations.DeleteModel(
            name='Gigs',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
