# Generated by Django 4.0.5 on 2023-08-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_gigs_service_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokens',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
