# Generated by Django 4.0.5 on 2023-09-12 17:30

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gigs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('gig_name', models.CharField(max_length=100)),
                ('gig_description', models.CharField(max_length=1000, null=True)),
                ('gig_price', models.CharField(max_length=20, null=True)),
                ('gig_negotiable', models.BooleanField(default=False, verbose_name='Negotiable')),
                ('gig_location', models.CharField(max_length=20, null=True)),
                ('gig_service_type', models.CharField(max_length=20, null=True)),
                ('gig_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='gig_image')),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gigs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now=True)),
                ('rating', models.FloatField(blank=True, default=0)),
                ('review_choice', models.CharField(blank=True, choices=[('service_completed', 'Service Completed'), ('mind_change', 'Mind Change'), ('service_provider_unavailable', 'SERVICE PROVIDER UNAVAILABLE')], max_length=255)),
                ('review_details', models.CharField(blank=True, max_length=1000, null=True)),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_gig', to='gigs.gigs')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_gigs', to='gigs.gigs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
