# Generated by Django 4.0.5 on 2023-08-01 10:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gigs',
            name='gig_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='gig_image'),
        ),
    ]
