# Generated by Django 4.0.5 on 2023-09-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
