# Generated by Django 4.0.5 on 2023-09-12 17:30

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Business_name', models.CharField(max_length=30, null=True)),
                ('experience', models.IntegerField()),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('alt_phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('service_title', models.CharField(max_length=100)),
                ('service_overview', models.CharField(max_length=1000, null=True)),
                ('service_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='service_image')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
